/**
 * Constants
 */
import { PERMISSIONS, PermissionType, RoleType } from "../constants/roles";

export const RolePermissions: Record<RoleType, Array<PermissionType>> = {
  OWNER: [
    PERMISSIONS.CREATE_WORKSPACE,
    PERMISSIONS.EDIT_WORKSPACE,
    PERMISSIONS.DELETE_WORKSPACE,
    PERMISSIONS.MANAGE_WORKSPACE_SETTINGS,

    PERMISSIONS.ADD_MEMBER,
    PERMISSIONS.CHANGE_MEMBER_ROLE,
    PERMISSIONS.REMOVE_MEMBER,

    PERMISSIONS.CREATE_PROJECT,
    PERMISSIONS.EDIT_PROJECT,
    PERMISSIONS.DELETE_PROJECT,

    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.EDIT_TASK,
    PERMISSIONS.DELETE_TASK,

    PERMISSIONS.VIEW_ONLY,
  ],
  ADMIN: [
    PERMISSIONS.ADD_MEMBER,
    PERMISSIONS.CREATE_PROJECT,
    PERMISSIONS.EDIT_PROJECT,
    PERMISSIONS.DELETE_PROJECT,
    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.EDIT_TASK,
    PERMISSIONS.DELETE_TASK,
    PERMISSIONS.MANAGE_WORKSPACE_SETTINGS,
    PERMISSIONS.VIEW_ONLY,
  ],
  MEMBER: [
    PERMISSIONS.VIEW_ONLY,
    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.EDIT_TASK,
  ],
};
